#!/usr/bin/env bash
# =============================================================================
# M0 orchestrator — deploy a 3-node Bondy cluster on Fly, run the capability
# probe on each node, and render FLY_FAULT_CAPABILITY.md (06 §M0 deliverable).
#
# Idempotent: safe to re-run. Reads nothing interactive except `fly auth login`
# (which you must have done first). Run from the REPO ROOT.
#
#   FLY_ORG=<org> FLY_REGION=<region> ./harness/m0-fly-spike/run-spike.sh
#
# Env (all optional): FLY_ORG (default leapsight), FLY_REGION (default lhr),
#                     M0_SKIP_DEPLOY=1 to probe an already-running cluster.
# =============================================================================
set -euo pipefail

# Needs bash 4+ (mapfile, associative arrays). macOS ships 3.2 as /bin/bash —
# use Homebrew bash (`brew install bash`) so `/usr/bin/env bash` finds it.
if [ "${BASH_VERSINFO:-0}" -lt 4 ]; then
  echo "ERROR: bash >= 4 required (found ${BASH_VERSION:-?}). Try: brew install bash" >&2
  exit 1
fi

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
APP="bondy-perf-m0"
ORG="${FLY_ORG:-leapsight}"
REGION="${FLY_REGION:-lhr}"
CONFIG="harness/m0-fly-spike/fly.toml"
DOCKERFILE="harness/m0-fly-spike/Dockerfile"
OUT="$HERE/out"
REPORT="$HERE/FLY_FAULT_CAPABILITY.md"
FAULTS=(net_admin_cap partition_iptables delay_tc_netem clock_skew_libfaketime disk_fill_fallocate cpu_stress_stressng signal_beam)

cd "$ROOT"
mkdir -p "$OUT"

say()  { printf '\n\033[1;34m==> %s\033[0m\n' "$*"; }
die()  { printf '\033[1;31mERROR: %s\033[0m\n' "$*" >&2; exit 1; }

# ---- 0. preflight -----------------------------------------------------------
command -v fly >/dev/null || die "flyctl not on PATH"
command -v jq  >/dev/null || die "jq not on PATH (brew install jq)"
fly auth whoami >/dev/null 2>&1 || die "not logged in — run:  fly auth login"
GITSHA="$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"
GITTAG="$(git describe --tags --exact-match 2>/dev/null || echo none)"

if [ "${M0_SKIP_DEPLOY:-0}" != "1" ]; then
  # ---- 1. app ---------------------------------------------------------------
  if ! fly apps list --json | jq -e --arg a "$APP" '.[]|select(.Name==$a)' >/dev/null 2>&1; then
    say "creating app $APP in org $ORG"
    fly apps create "$APP" --org "$ORG"
  fi

  # ---- 2. build + deploy (remote) -------------------------------------------
  say "deploying (remote build) — OTP-29 image of $GITSHA (tag $GITTAG)"
  fly deploy --config "$CONFIG" --dockerfile "$DOCKERFILE" \
    --app "$APP" --regions "$REGION" --remote-only --ha=false --yes

  # ---- 3. scale to 3 --------------------------------------------------------
  say "scaling to 3 machines in $REGION"
  fly scale count 3 --app "$APP" --region "$REGION" --yes
fi

# ---- 4. wait for health (3 started + checks passing) ------------------------
say "waiting for 3 healthy machines"
for i in $(seq 1 40); do
  started=$(fly machines list --app "$APP" --json | jq '[.[]|select(.state=="started")]|length')
  passing=$(fly machines list --app "$APP" --json \
            | jq '[.[]|.checks[]?|select(.status=="passing")]|length')
  printf '  [%2d/40] started=%s checks_passing=%s\n' "$i" "$started" "$passing"
  [ "${started:-0}" -ge 3 ] && [ "${passing:-0}" -ge 3 ] && break
  sleep 15
done
[ "${started:-0}" -ge 3 ] || die "cluster did not reach 3 started machines"

# ---- 5. topology ------------------------------------------------------------
mapfile -t IDS  < <(fly machines list --app "$APP" --json | jq -r '.[]|select(.state=="started")|.id')
mapfile -t IPS  < <(fly machines list --app "$APP" --json | jq -r '.[]|select(.state=="started")|.private_ip')
N=${#IDS[@]}
say "topology: $N nodes"
for i in "${!IDS[@]}"; do printf '  %s  %s\n' "${IDS[$i]}" "${IPS[$i]}"; done

# ---- 6. probe each node (peer = next node, ring) ----------------------------
rm -f "$OUT"/*.ndjson
for i in "${!IDS[@]}"; do
  id="${IDS[$i]}"; peer="${IPS[$(( (i+1) % N ))]}"
  say "probing $id (peer $peer)"
  # `fly ssh console` connects as root; pipe the LOCAL probe over stdin so probe
  # edits take effect without rebuilding/redeploying the image.
  if ! fly ssh console --app "$APP" --machine "$id" \
        -C "bash -s -- $peer eth0" < "$HERE/probe.sh" 2>"$OUT/$id.stderr" \
        | tee "$OUT/$id.ndjson"; then
    echo "  (probe on $id returned non-zero — see $OUT/$id.stderr)"
  fi
done
cat "$OUT"/*.ndjson > "$OUT/all.ndjson" 2>/dev/null || true

# ---- 7. render FLY_FAULT_CAPABILITY.md --------------------------------------
say "rendering $REPORT"
{
  echo "# FLY_FAULT_CAPABILITY.md"
  echo
  echo "**M0 fault-injection capability matrix** — generated by \`run-spike.sh\`."
  echo
  echo "- Bondy build: \`$GITSHA\` (tag \`$GITTAG\`)"
  echo "- App: \`$APP\` · org \`$ORG\` · region \`$REGION\` · nodes: \`$N\`"
  echo "- Generated: \`$(date -u +%Y-%m-%dT%H:%M:%SZ)\`"
  echo
  echo "Legend: ✅ confirmed on every node · ⚠️ partial · ❌ not confirmed / unavailable."
  echo "A fault is only trusted downstream (03 §5, 05 R1) when its row is ✅."
  echo
  echo "| Fault (probe id) | 03 §5 class | Nodes attempted | Nodes confirmed | Status |"
  echo "|---|---|---|---|---|"
  declare -A CLASS=(
    [net_admin_cap]="precondition (CAP_NET_ADMIN)"
    [partition_iptables]="partition"
    [delay_tc_netem]="delay / loss"
    [clock_skew_libfaketime]="clock_skew"
    [disk_fill_fallocate]="disk fill"
    [cpu_stress_stressng]="cpu stress"
    [signal_beam]="kill / pause (signal)"
  )
  for f in "${FAULTS[@]}"; do
    att=$(jq -rs --arg f "$f" '[.[]|select(.fault==$f and .attempted)]|length' "$OUT/all.ndjson" 2>/dev/null || echo 0)
    con=$(jq -rs --arg f "$f" '[.[]|select(.fault==$f and .confirmed)]|length' "$OUT/all.ndjson" 2>/dev/null || echo 0)
    status="❌"
    if   [ "${con:-0}" -ge "$N" ] && [ "$N" -gt 0 ]; then status="✅"
    elif [ "${con:-0}" -gt 0 ]; then status="⚠️"; fi
    printf '| `%s` | %s | %s/%s | %s/%s | %s |\n' "$f" "${CLASS[$f]}" "${att:-0}" "$N" "${con:-0}" "$N" "$status"
  done
  echo
  echo "## Fallback routing (03 §5)"
  echo
  echo "Any row that is not ✅ routes its fault class to the local-Docker substrate"
  echo "(\`just m0-local-*\` / 03 §6) for the runs that need it. No downstream milestone"
  echo "trusts a Fly network/clock fault whose row here is not ✅."
  echo
  echo "## Raw probe output"
  echo
  echo "Per-node NDJSON is in \`harness/m0-fly-spike/out/<machine-id>.ndjson\`."
} > "$REPORT"

say "done — see $REPORT"
echo "Tear down when finished:  just m0-down   (stop)   |   just m0-destroy  (delete app+volumes)"
