#!/bin/bash

set -e

NC='\033[0m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'

# Mustache Rebar3 variables will be replaced during release creation.
BONDY_RELEASE_DIR=./releases/{{release_version}}/

# We export this variables so that users can use them in bondy,conf.
# They will be replaced by replace-ev-vars below.
export BONDY_ERL_NODENAME="${BONDY_ERL_NODENAME:-bondy@127.0.0.1}"
export BONDY_ERL_DISTRIBUTED_COOKIE="${BONDY_ERL_DISTRIBUTED_COOKIE:-bondy}"
export BONDY_ETC_DIR={{platform_etc_dir}}
export BONDY_DATA_DIR={{platform_data_dir}}
export BONDY_LOG_DIR={{platform_log_dir}}
export BONDY_TMP_DIR={{platform_tmp_dir}}

echo "${GREEN}===> Running Bondy Rebar3 pre_start hook"
echo "${NC}===> BONDY_ERL_NODENAME=${BONDY_ERL_NODENAME}"
echo "${NC}===> BONDY_ERL_DISTRIBUTED_COOKIE=${BONDY_ERL_DISTRIBUTED_COOKIE}"
echo "${NC}===> BONDY_DATA_DIR=${BONDY_DATA_DIR}"
echo "${NC}===> BONDY_LOG_DIR=${BONDY_LOG_DIR}"
echo "${NC}===> BONDY_TMP_DIR=${BONDY_TMP_DIR}"
relx_escript ./bin/validate-config ${BONDY_ETC_DIR} ${BONDY_RELEASE_DIR}
relx_escript ./bin/replace-env-vars ${BONDY_ETC_DIR}
relx_escript ./bin/replace-env-vars ${BONDY_RELEASE_DIR}