#!/bin/bash

set -e

NC='\033[0m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
# This Rebar3 variable will be reaplced during release creation provided there
# is an overlay template action copying the file to the release.
export platform_bin_dir={{platform_bin_dir}}
export platform_data_dir={{platform_data_dir}}
export platform_etc_dir={{platform_etc_dir}}
export platform_lib_dir={{platform_lib_dir}}
export platform_log_dir={{platform_log_dir}}
export platform_tmp_dir={{platform_tmp_dir}}
BONDY_RELEASE_DIR=./releases/{{release_version}}/

echo "${GREEN}===> Running Bondy Rebar3 pre_start hook"
relx_escript ./bin/validate-config ${platform_etc_dir} ${BONDY_RELEASE_DIR}
relx_escript ./bin/replace-env-vars ${platform_etc_dir}
relx_escript ./bin/replace-env-vars ${BONDY_RELEASE_DIR}