# fly.toml app configuration file generated for bondy on 2023-10-10T19:44:48+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bondy"
primary_region = "lhr"
kill_signal = "SIGTERM"
kill_timeout = "30s"
# console_command = "bin/bondy remote_console"

[experimental]
  entrypoint = ["/bin/bash", "-c", "source /bondy/setup.sh && exec bin/bondy foreground"]

[build]
  image = "leapsight/bondy:develop-alpine"

[deploy]
  strategy = "rolling"

[env]
  BONDY_DATA_DIR = "/bondy/data"
  BONDY_ERL_DISTRIBUTED_COOKIE = "bondy"
  BONDY_LOG_LEVEL = "info"
  ERL_CRASH_DUMP = "/dev/null"
  ERL_DIST_PORT = "27784"

[http_service]
  internal_port = 18080
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0

  [http_service.concurrency]
    type = "connections"
    hard_limit = 16384
    soft_limit = 16384

[[services]]
  protocol = "tcp"
  internal_port = 18081

  [services.concurrency]
    type = "connections"
    hard_limit = 16384
    soft_limit = 16384

[checks]
  [checks.admin-http-alive]
    port = 18081
    type = "http"
    interval = "15s"
    timeout = "10s"
    grace_period = "30s"
    method = "get"
    path = "/ping"

[[files]]
  guest_path = "/bondy/setup.sh"
  local_path = "setup.sh"
  secret_name = ""
  raw_value = ""

[[files]]
  guest_path = "/bondy/etc/bondy.conf.template"
  local_path = "config/bondy.conf.template"
  secret_name = ""
  raw_value = ""

[[files]]
  guest_path = "/bondy/etc/security_config.json"
  local_path = "config/security_config.json"
  secret_name = ""
  raw_value = ""

[[metrics]]
  port = 18081
  path = "/metrics"
