%% =============================================================================
%% SPDX-FileCopyrightText: 2023 - 2026 Leapsight
%% SPDX-License-Identifier: Apache-2.0
%% =============================================================================
%%
%% Constants and record definitions shared by the bondy_oplog_wal modules.
%% -----------------------------------------------------------------------------

-ifndef(BONDY_OPLOG_WAL_HRL).
-define(BONDY_OPLOG_WAL_HRL, true).

%% -----------------------------------------------------------------------------
%% -----------------------------------------------------------------------------
%%
%% The log core lives in the `bondy_log` library app and owns every constant
%% below under a `BONDY_LOG_*` name (`bondy_log/include/bondy_log.hrl`). The
%% `BONDY_OPLOG_WAL_*` names are aliases kept so the oplog modules and their
%% tests are unchanged; new code includes `bondy_log.hrl` directly.

-include_lib("bondy_log/include/bondy_log.hrl").

-define(BONDY_OPLOG_WAL_BODY_COMPRESSION_MIN_BYTES_DEFAULT,
    ?BONDY_LOG_BODY_COMPRESSION_MIN_BYTES_DEFAULT
).
-define(BONDY_OPLOG_WAL_CODEC_ALGO_LZ4, ?BONDY_LOG_CODEC_ALGO_LZ4).
-define(BONDY_OPLOG_WAL_CODEC_ALGO_ZLIB, ?BONDY_LOG_CODEC_ALGO_ZLIB).
-define(BONDY_OPLOG_WAL_CODEC_CIPHER_AES_256_GCM,
    ?BONDY_LOG_CODEC_CIPHER_AES_256_GCM
).
-define(BONDY_OPLOG_WAL_CODEC_ENCRYPT_HEADER_BYTES,
    ?BONDY_LOG_CODEC_ENCRYPT_HEADER_BYTES
).
-define(BONDY_OPLOG_WAL_CODEC_IV_BYTES, ?BONDY_LOG_CODEC_IV_BYTES).
-define(BONDY_OPLOG_WAL_CODEC_KEY_BYTES, ?BONDY_LOG_CODEC_KEY_BYTES).
-define(BONDY_OPLOG_WAL_CODEC_KEY_ID_BYTES, ?BONDY_LOG_CODEC_KEY_ID_BYTES).
-define(BONDY_OPLOG_WAL_CODEC_TAG_BYTES, ?BONDY_LOG_CODEC_TAG_BYTES).
-define(BONDY_OPLOG_WAL_FRAME_FLAG_COMPRESSED,
    ?BONDY_LOG_FRAME_FLAG_COMPRESSED
).
-define(BONDY_OPLOG_WAL_FRAME_FLAG_CRC32C, ?BONDY_LOG_FRAME_FLAG_CRC32C).
-define(BONDY_OPLOG_WAL_FRAME_FLAG_ENCRYPTED, ?BONDY_LOG_FRAME_FLAG_ENCRYPTED).
-define(BONDY_OPLOG_WAL_FRAME_HEADER_BYTES, ?BONDY_LOG_FRAME_HEADER_BYTES).
-define(BONDY_OPLOG_WAL_FRAME_KNOWN_FLAGS_V1, ?BONDY_LOG_FRAME_KNOWN_FLAGS_V1).
-define(BONDY_OPLOG_WAL_FRAME_KNOWN_FLAGS_V2, ?BONDY_LOG_FRAME_KNOWN_FLAGS_V2).
%% "BDOP" in ASCII: the oplog's frame magic, the value
%% `bondy_oplog_log_adapter:frame_magic/0` returns. The log core has no
%% magic of its own; every log kind names one through its adapter.
-define(BONDY_OPLOG_WAL_FRAME_MAGIC, 16#42444F50).
-define(BONDY_OPLOG_WAL_FRAME_VERSION, ?BONDY_LOG_FRAME_VERSION).
-define(BONDY_OPLOG_WAL_FRAME_VERSION_V1, ?BONDY_LOG_FRAME_VERSION_V1).
-define(BONDY_OPLOG_WAL_FRAME_VERSION_V2, ?BONDY_LOG_FRAME_VERSION_V2).
-define(BONDY_OPLOG_WAL_IDX_DEFAULT_INTERVAL_BYTES,
    ?BONDY_LOG_IDX_DEFAULT_INTERVAL_BYTES
).
-define(BONDY_OPLOG_WAL_IDX_ENTRY_BYTES, ?BONDY_LOG_IDX_ENTRY_BYTES).
-define(BONDY_OPLOG_WAL_IDX_ENTRY_BYTES_V1, ?BONDY_LOG_IDX_ENTRY_BYTES_V1).
-define(BONDY_OPLOG_WAL_IDX_ENTRY_BYTES_V2, ?BONDY_LOG_IDX_ENTRY_BYTES_V2).
-define(BONDY_OPLOG_WAL_IDX_HEADER_BYTES, ?BONDY_LOG_IDX_HEADER_BYTES).
-define(BONDY_OPLOG_WAL_IDX_MAGIC, ?BONDY_LOG_IDX_MAGIC).
-define(BONDY_OPLOG_WAL_IDX_VERSION, ?BONDY_LOG_IDX_VERSION).
-define(BONDY_OPLOG_WAL_IDX_VERSION_V1, ?BONDY_LOG_IDX_VERSION_V1).
-define(BONDY_OPLOG_WAL_IDX_VERSION_V2, ?BONDY_LOG_IDX_VERSION_V2).
-define(BONDY_OPLOG_WAL_SEGMENT_HEADER_BYTES, ?BONDY_LOG_SEGMENT_HEADER_BYTES).
-define(BONDY_OPLOG_WAL_SEGMENT_MAGIC, ?BONDY_LOG_SEGMENT_MAGIC).
-define(BONDY_OPLOG_WAL_SEGMENT_VERSION, ?BONDY_LOG_SEGMENT_VERSION).

-define(BONDY_OPLOG_WAL_MANIFEST_VERSION, ?BONDY_LOG_MANIFEST_VERSION).
-define(BONDY_OPLOG_WAL_MANIFEST_FILENAME, ?BONDY_LOG_MANIFEST_FILENAME).
-define(BONDY_OPLOG_WAL_MANIFEST_TMP_FILENAME,
    ?BONDY_LOG_MANIFEST_TMP_FILENAME
).
-define(BONDY_OPLOG_WAL_CONSUMER_OFFSET_FILENAME,
    ?BONDY_LOG_CONSUMER_OFFSET_FILENAME
).
-define(BONDY_OPLOG_WAL_CONSUMER_OFFSET_TMP_FILENAME,
    ?BONDY_LOG_CONSUMER_OFFSET_TMP_FILENAME
).
-define(BONDY_OPLOG_WAL_CONSUMER_OFFSET_VERSION,
    ?BONDY_LOG_CONSUMER_OFFSET_VERSION
).
-define(BONDY_OPLOG_WAL_FSYNC_MODE_DEFAULT, ?BONDY_LOG_FSYNC_MODE_DEFAULT).
-define(BONDY_OPLOG_WAL_BATCHED_FSYNC_INTERVAL_DEFAULT_MS,
    ?BONDY_LOG_BATCHED_FSYNC_INTERVAL_DEFAULT_MS
).
-define(BONDY_OPLOG_WAL_BATCHED_FSYNC_BYTES_DEFAULT,
    ?BONDY_LOG_BATCHED_FSYNC_BYTES_DEFAULT
).
-define(BONDY_OPLOG_WAL_GROUP_COMMIT_DEFAULT, ?BONDY_LOG_GROUP_COMMIT_DEFAULT).
-define(BONDY_OPLOG_WAL_GROUP_COMMIT_MAX_DEFAULT,
    ?BONDY_LOG_GROUP_COMMIT_MAX_DEFAULT
).
-define(BONDY_OPLOG_WAL_MAX_BATCH_BYTES_DEFAULT,
    ?BONDY_LOG_MAX_BATCH_BYTES_DEFAULT
).
-define(BONDY_OPLOG_WAL_SNAPSHOT_WATERMARK_FILENAME,
    ?BONDY_LOG_SNAPSHOT_WATERMARK_FILENAME
).
-define(BONDY_OPLOG_WAL_SNAPSHOT_WATERMARK_TMP_FILENAME,
    ?BONDY_LOG_SNAPSHOT_WATERMARK_TMP_FILENAME
).
-define(BONDY_OPLOG_WAL_SNAPSHOT_WATERMARK_VERSION,
    ?BONDY_LOG_SNAPSHOT_WATERMARK_VERSION
).
-define(BONDY_OPLOG_WAL_MIN_LIVE_SEGMENTS_DEFAULT,
    ?BONDY_LOG_MIN_LIVE_SEGMENTS_DEFAULT
).
-define(BONDY_OPLOG_WAL_RETENTION_SWEEP_INTERVAL_DEFAULT_MS,
    ?BONDY_LOG_RETENTION_SWEEP_INTERVAL_DEFAULT_MS
).
-define(BONDY_OPLOG_WAL_MAX_TOTAL_WAL_SIZE_DEFAULT,
    ?BONDY_LOG_MAX_TOTAL_WAL_SIZE_DEFAULT
).
-define(BONDY_OPLOG_WAL_MAX_LIVE_SEGMENTS_DEFAULT,
    ?BONDY_LOG_MAX_LIVE_SEGMENTS_DEFAULT
).
-define(BONDY_OPLOG_WAL_WAL_FULL_TELEMETRY_DEBOUNCE_MS,
    ?BONDY_LOG_WAL_FULL_TELEMETRY_DEBOUNCE_MS
).

-endif.
