%% =============================================================================
%% SPDX-FileCopyrightText: 2016 - 2026 Leapsight
%% SPDX-License-Identifier: Apache-2.0
%% =============================================================================

-module(bondy_connect_transport_tls_SUITE).

-moduledoc """
What is specific to **raw WAMP over TLS**, against the live `wamp_tls` listener
(port 18085, enabled in `bondy_ct`).

Carrying WAMP over this transport is not tested here — every WAMP use case runs
on `tls` in `bondy_connect_conformance_SUITE`, and its specs already dial with
`verify => verify_peer` and the test CA bundle, so the verified happy path is
exercised by all of them rather than by one case here.

What no other suite can assert is the **negative**: that verification refuses a
chain it cannot anchor. A `verify_peer` that accepted anything would leave every
one of those conformance runs green while providing no security at all, which is
exactly the failure a positive round-trip cannot see.
""".

-include_lib("common_test/include/ct.hrl").
-include_lib("stdlib/include/assert.hrl").
-include_lib("bondy_wamp/include/bondy_wamp.hrl").
-include("bondy_connect.hrl").

-compile([nowarn_export_all, export_all]).

-define(REALM, <<"com.example.bondy_connect.m5.tls">>).
-define(HOST, "127.0.0.1").
-define(PORT, 18085).

all() ->
    [
        verify_peer_rejects_untrusted_ca
    ].

init_per_suite(Config) ->
    bondy_ct:start_bondy(),
    {ok, _} = application:ensure_all_started(bondy_connect_sdk),
    ok = add_anon_realm(?REALM),
    %% Resolve the CA bundle absolutely now (cwd is the project root at suite
    %% init) so it stays valid regardless of any later cwd change.
    CACertFile = filename:absname("./etc/ssl/server/cacert.pem"),
    true = filelib:is_regular(CACertFile),
    [{cacertfile, CACertFile} | Config].

end_per_suite(_) ->
    ok.

%% =============================================================================
%% TESTS
%% =============================================================================

%% A full register→call works over the TLS transport.
add_anon_realm(RealmUri) ->
    Cfg = #{
        uri => RealmUri,
        authmethods => [?WAMP_ANON_AUTH],
        security_enabled => true,
        grants => [
            #{
                permissions => [
                    <<"wamp.register">>,
                    <<"wamp.unregister">>,
                    <<"wamp.call">>,
                    <<"wamp.subscribe">>,
                    <<"wamp.publish">>
                ],
                uri => <<"">>,
                match => <<"prefix">>,
                roles => [<<"anonymous">>]
            }
        ],
        sources => [
            #{
                usernames => [<<"anonymous">>],
                authmethod => ?WAMP_ANON_AUTH,
                cidr => <<"0.0.0.0/0">>
            }
        ]
    },
    _ = bondy_realm:create(Cfg),
    ok.

-doc """
`verify_peer` without a CA that can anchor the server's chain fails, and fails
in the TLS handshake rather than later.

The server certificate is signed by the repo's test CA (`etc/ssl/server`,
regenerated by `just certs`), which no system trust store holds — so omitting
`cacertfile` leaves the client unable to build a chain. The alert is matched,
not merely `{error, _}`: a connection that failed for a wrong port or a missing
realm would satisfy a loose assertion just as well and prove nothing about
verification.
""".
verify_peer_rejects_untrusted_ca(_) ->
    ?assertMatch(
        {error, {shutdown, {connect_error, {tls_alert, {unknown_ca, _}}}}},
        bondy_connect_client:connect(#{
            transport => tls,
            endpoint => {?HOST, ?PORT},
            realm => ?REALM,
            auth => #{method => ?WAMP_ANON_AUTH},
            serializers => [json],
            tls => #{verify => verify_peer, server_name_indication => disable}
        })
    ).
