%% =============================================================================
%%  bondy_security.hrl -
%%
%%  Copyright (c) 2016-2021 Leapsight. All rights reserved.
%%
%%  Licensed under the Apache License, Version 2.0 (the "License");
%%  you may not use this file except in compliance with the License.
%%  You may obtain a copy of the License at
%%
%%     http://www.apache.org/licenses/LICENSE-2.0
%%
%%  Unless required by applicable law or agreed to in writing, software
%%  distributed under the License is distributed on an "AS IS" BASIS,
%%  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
%%  See the License for the specific language governing permissions and
%%  limitations under the License.
%% =============================================================================



-define(BONDY_AUTH_PROVIDER, <<"com.leapsight.bondy.rbac">>).

-define(WAMP_ANON_AUTH,         <<"anonymous">>).
-define(PASSWORD_AUTH,          <<"password">>).
-define(OAUTH2_AUTH,            <<"oauth2">>).
-define(TRUST_AUTH,             <<"trust">>).
-define(WAMP_COOKIE_AUTH,       <<"cookie">>).
-define(WAMP_CRA_AUTH,          <<"wampcra">>).
-define(WAMP_CRYPTOSIGN_AUTH,   <<"cryptosign">>).
-define(WAMP_OAUTH2_AUTH,       ?OAUTH2_AUTH).
-define(WAMP_SCRAM_AUTH,        <<"wamp-scram">>).
-define(WAMP_TICKET_AUTH,       <<"ticket">>).
-define(WAMP_TLS_AUTH,          <<"tls">>).

-define(BONDY_AUTHMETHODS_INFO, #{
    ?WAMP_ANON_AUTH => #{
        callback_mod => bondy_auth_anonymous,
        description => <<"Allows access to clients which connect without credentials, assigning them as members of the 'anonymous' group. You can configure the allowed sources for the anonymous user and the permissions assigned to the anonymous group - but you cannot make the anonymous group a member of another group.">>
    },
    ?TRUST_AUTH => #{
        callback_mod => bondy_auth_trust,
        description => <<"Allows access to clients which connect with an existing username (WAMP authid field) but does not request them to authenticate. This is to be used in conjunction with source definition e.g. trust only clients within a defined network (CIDR).">>
    },
    ?PASSWORD_AUTH => #{
        callback_mod => bondy_auth_password,
        description => <<"Allows access to clients which connect with an existing username (WAMP authid field) and password, where the password is send in clear-text and is therefore vulnerable to password \"sniffing\" attacks, unless the connection is protected by TLS encryption. It should be avoided and replaced by the use of \"wamp-cra\" or \"wamp-scram\" challenge-response methods if possible.">>
    },
    ?OAUTH2_AUTH => #{
        callback_mod => bondy_auth_oauth2
    },
    ?WAMP_COOKIE_AUTH => #{
        callback_mod => undefined
    },
    ?WAMP_CRA_AUTH => #{
        callback_mod => bondy_auth_wamp_cra
    },
    ?WAMP_SCRAM_AUTH => #{
        callback_mod => bondy_auth_wamp_scram
    },
    ?WAMP_CRYPTOSIGN_AUTH => #{
        callback_mod => bondy_auth_wamp_cryptosign
    },
    ?WAMP_TICKET_AUTH => #{
        callback_mod => bondy_auth_ticket,
        description => <<"Allows access to clients which connect with an existing username (WAMP authid field) and a ticket previoulsy generated by Bondy. If the transport is not encrypted, this method is vulnerable to ticket \"sniffing\" attacks, a man-in-the-middle can sniff and possibly hijack the ticket. If the ticket value is reused, that might enable replay attacks. It should be used only when the connection is protected by TLS encryption.">>
    },
    ?WAMP_TLS_AUTH => #{
        callback_mod => undefined
    }
}).


-define(BONDY_AUTH_METHOD_NAMES,
    case persistent_term:get({bondy, '_auth_method_names'}, undefined) of
        undefined ->
            Names = maps:keys(?BONDY_AUTHMETHODS_INFO),
            ok = persistent_term:put({bondy, '_auth_method_names'}, Names),
            Names;
        Names ->
            Names
    end
).

-define(WAMP_PERMISSIONS, [
    <<"wamp.register">>,
    <<"wamp.unregister">>,
    <<"wamp.call">>,
    <<"wamp.cancel">>,
    <<"wamp.subscribe">>,
    <<"wamp.unsubscribe">>,
    <<"wamp.publish">>,
    <<"wamp.disclose_caller">>,
    <<"wamp.disclose_publisher">>,
    <<"wamp.disclose_session_info">>
]).

-define(BONDY_PERMISSIONS, [
    <<"bondy.issue">>,
    <<"bondy.revoke">>,
    <<"bondy.authenticate">>
]).
