@startuml

participant caller
participant bondy_ws_handler_1
participant bondy_router
participant bondy_call_queue
participant bondy_router_2
participant bondy_ws_handler_2
participant callee

activate bondy_ws_handler_1
activate bondy_ws_handler_2
caller -> bondy_ws_handler_1: call(CallerID,...)
activate bondy_router
bondy_ws_handler_1 -> bondy_router: call(CallerID,...)
bondy_router -> bondy_call_queue: add(InvReqId, CallReqId, CallerId)
bondy_router -> bondy_ws_handler_2: invocation(InvReqId,...)
bondy_ws_handler_2 -> callee: invocation(InvReqId,...)
deactivate bondy_router
callee -> bondy_ws_handler_2: yield
activate bondy_router_2
bondy_ws_handler_2 -> bondy_router_2: yield
bondy_router_2 -> bondy_call_queue: caller_id(InvReqId)
bondy_call_queue -> bondy_router_2: pid()
bondy_router_2 -> bondy_ws_handler_1: result(CallReqId,...)
bondy_ws_handler_1 -> caller: result(CallReqId,...)
deactivate bondy_router_2
@enduml
