name: Bondy Debian OTP 27
on:
  workflow_dispatch:
  push:
    branches : [master, develop]
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-[a-zA-Z0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-[a-zA-Z0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+.[0-9]+'

jobs:

  build-push-arm64:
    runs-on: ubuntu-24-arm64-4x

    steps:
      # Not strictly required as it should default based on runner)
      - name: Set Platform to arm64
        run: echo "DOCKER_DEFAULT_PLATFORM=linux/arm64" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
          endpoint: builders

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # without registry name, we will add it in the build-push-action as
          # each registry has diff namespace at the moment
          images: |
            bondy
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
          flavor: |
            latest=false
            prefix=
            suffix=
          labels: |
            maintainer=Leapsight
            org.opencontainers.image.title=Bondy
            org.opencontainers.image.description=Bondy is an open source, always-on and scalable application networking platform connecting all elements of a distributed application—offering event and service mesh capabilities combined. From web and mobile apps to IoT devices and backend microservices, Bondy allows everything to talk using one simple communication protocol.
            org.opencontainers.image.vendor=Leapsight

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          sbom: true
          provenance: mode=max
          push: true
          context: .
          file: ./deployment/Dockerfile
          tags: leapsight/${{ steps.meta.outputs.tags }}-arm64

  build-push-x64:
    runs-on: ubuntu-latest

    steps:
      # Not strictly required as it should default based on runner)
      - name: Set Platform to amd64
        run: echo "DOCKER_DEFAULT_PLATFORM=linux/amd64" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
          endpoint: builders

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # without registry name, we will add it in the build-push-action as
          # each registry has diff namespace at the moment
          images: |
            bondy
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
          flavor: |
            latest=false
            prefix=
            suffix=
          labels: |
            maintainer=Leapsight
            org.opencontainers.image.title=Bondy
            org.opencontainers.image.description=Bondy is an open source, always-on and scalable application networking platform connecting all elements of a distributed application—offering event and service mesh capabilities combined. From web and mobile apps to IoT devices and backend microservices, Bondy allows everything to talk using one simple communication protocol.
            org.opencontainers.image.vendor=Leapsight

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          sbom: true
          provenance: mode=max
          push: true
          context: .
          file: ./deployment/Dockerfile
          tags: leapsight/${{ steps.meta.outputs.tags }}-amd64
          labels: ${{ steps.meta.outputs.labels }}

  create-manifests:
    runs-on: ubuntu-latest
    needs: [build-push-x64, build-push-arm64]

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # without registry name, we will add it in the build-push-action as
          # each registry has diff namespace at the moment
          images: |
            bondy
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
          flavor: |
            latest=false
            prefix=
            suffix=
          labels: |
            maintainer=Leapsight
            org.opencontainers.image.title=Bondy
            org.opencontainers.image.description=Bondy is an open source, always-on and scalable application networking platform connecting all elements of a distributed application—offering event and service mesh capabilities combined. From web and mobile apps to IoT devices and backend microservices, Bondy allows everything to talk using one simple communication protocol.
            org.opencontainers.image.vendor=Leapsight

      - name: Create branch/tag manifest and push
        run: |
          docker buildx imagetools create \
            -t leapsight/${{ steps.meta.outputs.tags }}  \
            leapsight/${{ steps.meta.outputs.tags }}-amd64 \
            leapsight/${{ steps.meta.outputs.tags }}-arm64
          docker buildx imagetools inspect \
            leapsight/${{ steps.meta.outputs.tags }}

      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      -
        # Copy multiplatform image from dockerhub to Github Registry
        # without changing the image SHA
        name: Copy Image to GitHub Container Registry
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: docker.io/leapsight/${{ steps.meta.outputs.tags }}
          dst: |
            ghcr.io/bondy-io/${{ steps.meta.outputs.tags }}
